from django.contrib import admin
from app1.models import  Bagitem,Chatbox,Club, Story,Customer ,Seller , Followrequest, Product , Order , Tag , Post, Comment,Review , Ratings, Transfer , Pay , Lvl1tags , Lvl2tags , Lvl3tags , Lvl4tags , Lvl5tags
# Register your models here.
admin.site.register(Bagitem)
admin.site.register(Customer)
admin.site.register(Product)
admin.site.register(Tag)
admin.site.register(Order)
admin.site.register(Seller)
admin.site.register(Post)
admin.site.register(Chatbox)
admin.site.register(Comment)
admin.site.register(Ratings)
admin.site.register(Review)
admin.site.register(Transfer)
admin.site.register(Pay)
admin.site.register(Followrequest)
admin.site.register(Lvl1tags)
admin.site.register(Lvl2tags)
admin.site.register(Lvl3tags)
admin.site.register(Lvl4tags)
admin.site.register(Lvl5tags)
admin.site.register(Club)
admin.site.register(Story)
