# Generated by Django 3.2.7 on 2021-12-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_post_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.seller'),
        ),
    ]
