# Generated by Django 3.2.7 on 2021-12-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode_of_payment',
            field=models.CharField(choices=[('CASH', 'CASH'), ('GPAY', 'GPAY')], max_length=30, null=True),
        ),
    ]
