# Generated by Django 3.2.7 on 2021-12-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_chatbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
