# Generated by Django 3.2.7 on 2021-12-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_chatbox_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='_app1_customer_followers_+', to='app1.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='following',
            field=models.ManyToManyField(null=True, related_name='_app1_customer_following_+', to='app1.Customer'),
        ),
    ]
