# Generated by Django 3.2.7 on 2022-01-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_customer_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='following',
        ),
        migrations.AddField(
            model_name='customer',
            name='followings',
            field=models.ManyToManyField(null=True, related_name='following', to='app1.Customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='follower', to='app1.Customer'),
        ),
    ]
