# Generated by Django 3.2.7 on 2022-01-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20220103_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(related_name='posts_liked', to='app1.Customer'),
        ),
    ]
