# Generated by Django 3.2.7 on 2022-01-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_comment_number_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_block',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
