# Generated by Django 3.2.7 on 2022-01-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_comment_is_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='number_of_likes',
        ),
        migrations.AddField(
            model_name='product',
            name='likers',
            field=models.ManyToManyField(related_name='products_liked', to='app1.Customer'),
        ),
    ]
