# Generated by Django 3.2.7 on 2022-01-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_ratings_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
