# Generated by Django 3.2.7 on 2022-01-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_seller_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField(default=0, null=True)),
                ('giver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giver', to='app1.customer')),
                ('taker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taker', to='app1.customer')),
            ],
        ),
    ]
