# Generated by Django 3.2.7 on 2022-01-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mode_of_payment',
            field=models.CharField(choices=[('CASH', 'CASH'), ('GPAY', 'GPAY'), ('VNITS', 'VNITS')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transaction Failed', 'Transaction Failed'), ('Transaction Successful', 'Transaction Successful'), ('Transaction to be verfied', 'Transaction to be verified'), ('Refund Request Active', 'Refund Request Active'), ('Refund Successful', 'Refund Successful')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Lvl1tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections1', models.ManyToManyField(null=True, related_name='connections1', to='app1.Customer')),
                ('parent1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent1', to='app1.customer')),
                ('post1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post1', to='app1.post')),
            ],
        ),
    ]
