# Generated by Django 3.2.7 on 2022-01-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20220108_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lvl2tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections2', models.ManyToManyField(null=True, related_name='connections2', to='app1.Customer')),
                ('parent2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent2', to='app1.customer')),
                ('post2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post2', to='app1.post')),
            ],
        ),
    ]
