# Generated by Django 3.2.7 on 2022-01-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_lvl2tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lvl5tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections5', models.ManyToManyField(null=True, related_name='connections5', to='app1.Customer')),
                ('parent5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent5', to='app1.customer')),
                ('post5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post5', to='app1.post')),
            ],
        ),
        migrations.CreateModel(
            name='Lvl4tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections4', models.ManyToManyField(null=True, related_name='connections4', to='app1.Customer')),
                ('parent4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent4', to='app1.customer')),
                ('post4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post4', to='app1.post')),
            ],
        ),
        migrations.CreateModel(
            name='Lvl3tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections3', models.ManyToManyField(null=True, related_name='connections3', to='app1.Customer')),
                ('parent3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent3', to='app1.customer')),
                ('post3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post3', to='app1.post')),
            ],
        ),
    ]
