# Generated by Django 3.2.7 on 2022-01-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_lvl1tags_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lvl1tags',
            name='name',
        ),
    ]
