# Generated by Django 3.2.7 on 2022-01-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_remove_lvl1tags_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lvl1tags',
            old_name='id',
            new_name='selfid',
        ),
    ]
