# Generated by Django 3.2.7 on 2022-01-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_rename_id_lvl1tags_selfid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lvl1tags',
            old_name='selfid',
            new_name='id',
        ),
        migrations.AddField(
            model_name='lvl1tags',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
