# Generated by Django 3.2.7 on 2022-01-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_auto_20220109_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvl2tags',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
