# Generated by Django 3.2.7 on 2022-01-25 15:27

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_lvl2tags_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='crushed',
            field=models.ManyToManyField(null=True, related_name='crushed_list', to='app1.Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='interested',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default=app1.models.get_default_profile_image, max_length=255, null=True, upload_to='customerprofileimages/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile_image',
            field=models.ImageField(blank=True, default=app1.models.get_default_profile_image, null=True, upload_to='postprofileimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile_image1',
            field=models.ImageField(blank=True, default=app1.models.get_default_profile_image, max_length=255, null=True, upload_to='productprofileimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile_image2',
            field=models.ImageField(blank=True, default=app1.models.get_default_profile_image, max_length=255, null=True, upload_to='productprofileimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile_image3',
            field=models.ImageField(blank=True, default=app1.models.get_default_profile_image, max_length=255, null=True, upload_to='productprofileimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile_image4',
            field=models.ImageField(blank=True, default=app1.models.get_default_profile_image, max_length=255, null=True, upload_to='productprofileimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile_image5',
            field=models.ImageField(blank=True, default=app1.models.get_default_profile_image, max_length=255, null=True, upload_to='productprofileimages/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='sellerprofileimages/'),
        ),
    ]
