# Generated by Django 3.2.7 on 2022-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_auto_20220125_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_of_comments',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
