# Generated by Django 3.2.7 on 2022-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_post_num_of_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_of_comments',
        ),
        migrations.AddField(
            model_name='customer',
            name='security',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
