# Generated by Django 3.2.7 on 2022-03-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_customer_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='customerprofileimages/13ry.jpg', max_length=255, null=True, upload_to='customerprofileimages/'),
        ),
        migrations.CreateModel(
            name='Followrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_status', models.BooleanField(default=False, null=True)),
                ('experiencer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiencer', to='app1.customer')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider', to='app1.customer')),
            ],
        ),
    ]
