# Generated by Django 3.2.7 on 2022-03-23 13:04

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_followrequest_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('profile_image', models.ImageField(blank=True, default=app1.models.get_default_profile_image, null=True, upload_to='clubprofileimages/')),
                ('creation_fees', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fees_to_enter', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='app1.customer')),
                ('members', models.ManyToManyField(related_name='members', to='app1.Customer')),
                ('trustee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trustee', to='app1.customer')),
            ],
        ),
    ]
