# Generated by Django 3.2.7 on 2022-03-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_club_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_private',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
