# Generated by Django 4.0.3 on 2022-03-24 12:09

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_club_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cover_image',
            field=models.ImageField(blank=True, default=app1.models.get_default_profile_image, null=True, upload_to='clubprofileimages/'),
        ),
        migrations.AddField(
            model_name='club',
            name='elites',
            field=models.ManyToManyField(related_name='elites', to='app1.customer'),
        ),
    ]
