# Generated by Django 4.0.3 on 2022-03-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='date_created',
            new_name='created_date',
        ),
    ]
