# Generated by Django 4.0.3 on 2022-03-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_rename_date_created_story_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='viewers',
            field=models.ManyToManyField(null=True, related_name='viewers', to='app1.customer'),
        ),
    ]
