# Generated by Django 4.0.3 on 2022-05-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_story_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode_of_payment',
            field=models.CharField(choices=[('CASH', 'CASH'), ('Gpay Confirmation Call', 'Gpay Confirmation Call')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.ManyToManyField(related_name='itemcontent', to='app1.product')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.customer')),
            ],
        ),
    ]
