# Generated by Django 4.0.3 on 2022-05-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='returnperiod',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
